### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hickford**
Add installation instructions

### CODE REVIEW

**Comment by bebehei** [comment]
:+1: People, who are not familiar to go won't know how to install it!

**Comment by ivanr** [comment]
@hickford apologies for not responding earlier. I have a couple of questions about your proposed installation method.

1. This pull request is for the stable branch,  but installing ssllabs-scan in the way you describe compiles form the master, meaning the development version that might be unstable. At the very least, the instructions in the stable version should install the stable version.

2. After the installation, the resulting binary wasn't on my path so I had to hunt for it. I did find it eventually in ~/go/bin. Are users supposed to add this location to the path manually? If so, there should be a mention of it in the docs. In fact, there should probably be one line there that we're just using an installation mechanism provided by go.

**Comment by hickford** [comment]
Hi Ivan. Pardon me I didn't realise there were binaries on the Releases page. That's much easier.

**Comment by ivanr** [comment]
@hickford Does that mean that you're abandoning this pull request?

**Comment by hickford** [comment]
I've updated the pull request. Reopen.

**Comment by hickford** [comment]
Could you reopen? It won't let me

**Pull request closed without merging**
