### PR TITLE
make some idiomatic improvements to the codebase

### PR DESCRIPTION
**Pull request by theckman**
This changeset makes no logic / behavioral changes to the application. This just pulls in some well-known idioms to make it read more like other Go projects:

* use the camel-case format for variable and constant names instead of snake-case
* when if block ends with a return statement, avoid the else block
* use var() and import() blocks instead of single-line statements
* in variable/function names, `Id` should be `ID`, `Http` should be `HTTP`, and `Api` should be `API`

`goimports`, `golint`, `go vet` were used to find/fix these issues.

### CODE REVIEW

**Comment by cognusion** [comment]
Whoa there.. you're fundamentally changing variable names, and a lot of them aren't just simple re-casing. 
    -	for _, value := range kIndex {
    +	for _, value := range index {

:thumbsdown:

**Comment by theckman** [comment]
Yes, correct. I opened this PR to help make this codebase more idiomatic. Depending how you look at things, there were fundamental changes needed to align with usual idioms. These are expected especially with struct member names in exported structs. This PR was just an initial pass at doing so while looking for feedback.

In respect to your example, if you have a preferred variable name I'll happily adjust the PR.

**Comment by ivanr** [comment]
For what it's worth, this pull request is not forgotten. But, being a Go novice, I need time to understand what is and isn't idiomatic.

**Comment by ivanr** [comment]
I haven't had the chance to research idiomatic Go, but I'll take your word for it. However, this pull request is for the stable branch. Please apply the changes to the latest master version and submit a pull request back to master. Thanks.

**Comment by ivanr** [comment]
Another thing, if you can please split the pull request into two: one to change field names and another if you want to make any changes to the flow (braces and such). Thanks.

**Pull request closed without merging**
